[package]
name = "dfa_lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
clap = { version = "4.5.50", features = ["derive"] }